repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.1.0
      hooks:
      -   id: trailing-whitespace
      -   id: end-of-file-fixer
      -   id: check-docstring-first
      -   id: check-json
      -   id: check-added-large-files
      -   id: debug-statements
      -   id: name-tests-test
      -   id: requirements-txt-fixer
  - repo: https://github.com/awslabs/git-secrets
    rev: 80230afa8c8bdeac766a0fece36f95ffaa0be778
    hooks:
      - id: git-secrets
        verbose: true
        entry: 'git-secrets --register-aws'
        language: script
        name: git-secrets-register-aws-provider
      - id: git-secrets
        verbose: true
        entry: 'git-secrets --scan'
        language: script
        name: git-secrets-scan
  - repo: https://github.com/markdownlint/markdownlint
    rev: v0.11.0
    hooks:
      - id: markdownlint
        name: Markdownlint
        description: Run markdownlint on your Markdown files
        entry: mdl .
        language: ruby
        files: \.(md|mdown|markdown)$
        verbose: true
        args:
          - "-s"
          - "mdl_style.rb"
  -   repo: https://github.com/awslabs/cfn-python-lint
      rev: v0.59.1
      hooks:
      -   id: cfn-python-lint
          files: src/.*(Cfn)\.(yml|yaml)$
